// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjgU33EUN6U_LnqEOFjkFlP2RQYA893Js',
    appId: '1:396820470969:web:3e221df1f1f7150f604f68',
    messagingSenderId: '396820470969',
    projectId: 'prostudy-51534',
    authDomain: 'prostudy-51534.firebaseapp.com',
    storageBucket: 'prostudy-51534.firebasestorage.app',
    measurementId: 'G-J2BE3J3ZNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGoe4p-yAAVRDUpyA5xRqAd2JdxKNxvH4',
    appId: '1:396820470969:android:3d7c5fccbc28deac604f68',
    messagingSenderId: '396820470969',
    projectId: 'prostudy-51534',
    storageBucket: 'prostudy-51534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3KwoQSCd4gr3XU3bmwPTrHiNHb3nKTbY',
    appId: '1:396820470969:ios:990e91f3f4bd5270604f68',
    messagingSenderId: '396820470969',
    projectId: 'prostudy-51534',
    storageBucket: 'prostudy-51534.firebasestorage.app',
    iosBundleId: 'com.nstar.prostudy',
  );
}
